WebUI testing

diff --git a/rss-bridge/rootfs/etc/services.d/rss-bridge/run b/rss-bridge/rootfs/etc/services.d/rss-bridge/run
--- a/rss-bridge/rootfs/etc/services.d/rss-bridge/run
+++ b/rss-bridge/rootfs/etc/services.d/rss-bridge/run
@@ -1,2 +1,4 @@
 #!/usr/bin/with-contenv bash
+set -e  # Exit immediately on error
+echo "Starting Apache2..."
 exec httpd -D FOREGROUND
